# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    addToPath: true
- script: sudo apt-get install -qqy --no-install-recommends apt-utils ffmpeg sox libcairo2-dev texlive texlive-fonts-extra texlive-latex-extra texlive-latex-recommended texlive-science tipa
  displayName: "Install system dependencies"
- script: sudo chmod +x ~/work/1/s/install.sh && ~/work/1/s/install.sh
  displayName:  "Install dependencies"

- script: manim phase-space.py PendulumCirclingOrigin -m
  displayName: "Generate PendulumCirclingOrigin"

- script: manim phase-space.py UnstableFeedForwardAtHorizontal -m
  displayName: "Generate UnstableFeedForwardAtHorizontal"

- script: manim phase-space.py LowFeedbackWithArmAtHorizontal -m
  displayName: "Generate LowFeedbackWithArmAtHorizontal"

- script: manim phase-space.py HighFeedback -m
  displayName: "Generate HighFeedback"

- script: manim phase-space.py ShowMultipleFeedback -m
  displayName: "Generate ShowMultipleFeedback"

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'Publish 720p30'
    targetPath: 'videos/phase-space/720p30/'

- task: UniversalPackages@0
  displayName: Universal Publish
  inputs:
    command: publish
    publishDirectory: 'videos/phase-space/720p30/'
    vstsFeedPublish: 'state-space-animations'
    vstsFeedPackagePublish: 'state-space-animations'
    packagePublishDescription: 'state space animations'

